### ISSUE TITLE
Please push 0.4.2

### ISSUE THREAD

**Issue by gnomff** [jasongoodwin/authentikat-jwt#26]
There was a version bump in json4s that broke binary compatibility (https://github.com/json4s/json4s/issues/212). I would love to use this library in my project but I need a later version of json4s than is used in 0.4.1. It looks like 0.4.2 has solved the problem, but it hasn't been pushed up to the maven repo. If someone could just push the latest version to maven it would really help me out. Thanks!

**Comment by jasongoodwin** [comment]
Hey sorry - just saw this. I'll try to do it in the next few days.

**Comment by gnomff** [comment]
Great, thanks!

**Comment by gnomff** [comment]
Hey, sorry to bug you, but I'd still really like to have 0.4.2

**Comment by jasongoodwin** [comment]
MAINTAINER FAIL.
I'll work on the code right now and hopefully push it tonight. Will confirm back shortly.

**Comment by jasongoodwin** [comment]
Sorry again - not sure how I missed publishing that ver. I published 0.4.3 w/ the most recent json4s libs.
I'll publish 0.4.2 if needed.

**Comment by jasongoodwin** [comment]
Is that okay for you using the latest json4s? Let me know or I can push 0.4.2 - just figured I'd brush it up whilst looking.

**Comment by gnomff** [comment]
Sorry I fell off the earth - 0.4.3 works perfectly, thank you!
