### ISSUE TITLE
Please, support Scala 2.12!

### ISSUE THREAD

**Issue by DanielaSfregola** [jasongoodwin/authentikat-jwt#28]
Please, release a version compatible with Scala 2.12

**Comment by DanielaSfregola** [comment]
I opened a PR that adds the support. See #29

**Comment by jasongoodwin** [comment]
Hey thanks! I'll put a reminder in my calendar to dig out my old laptop and publish this.

**Comment by DanielaSfregola** [comment]
Any chance to see the PR merged soon? Unfortunately, this is quite important for us as it is blocking us from upgrading to Scala 2.12

**Comment by jasongoodwin** [comment]
Sorry sorry - I'll do it today. Starting a company - life has been hectic.

**Comment by DanielaSfregola** [comment]
Please, let me know when a compatible version for scala 2.12 has been released

**Comment by jasongoodwin** [comment]
0.4.4 should be available.

**Comment by DanielaSfregola** [comment]
Awesome, thank you!
