### ISSUE TITLE
Broken header serialization in v0.4.4

### ISSUE THREAD

**Issue by DanielaSfregola** [jasongoodwin/authentikat-jwt#30]
With version 0.4.4 the JwtHeader is wrongly trasformed as 
```scala
[{"alg":"HS256"},{"typ":"JWT"}]
```
instead of
```scala
{"alg":"HS256","typ":"JWT"}
```

This is because in the JwtHeader class, in the `asJsonString` function we do:
```scala
    implicit val formats = org.json4s.DefaultFormats
    org.json4s.jackson.Serialization.write(toSerialize)
```
instead of 
```scala
SimpleJsonSerializer(toSerialize)
```

Please please fix it as this is making impossible to use the library!

Cheers,
D.

**Comment by DanielaSfregola** [comment]
any update on this at all?

**Comment by jasongoodwin** [comment]
Hey thanks, 
I removed the SimpleJsonLibrary as it may be vulnerable to injection attacks.
I'll look at this right now.

**Comment by jasongoodwin** [comment]
Ah sorry - you know what - the tests weren't being run as I included one failing test. For some reason it aborted the other ones so I didn't notice the issue. Give me a few - shouldn't be too hard to correct.

**Comment by jasongoodwin** [comment]
Alright, I'm publishing the fix. Thanks for waiting - I know it took a while for me to get this to you!!

**Comment by jasongoodwin** [comment]
0.4.5 published - it looks good.
