### ISSUE TITLE
support for RS256 algorithm

### ISSUE THREAD

**Issue by yogeshpathade** [jasongoodwin/authentikat-jwt#37]
I see currently the RS256 is not supported. Can it be easily implemented? I need it for my project to validate the JWT which is RS256.

Message: java.lang.UnsupportedOperationException: RS256 is an unknown or unimplemented JWT algo key
authentikat.jwt.JsonWebSignature$.apply(JsonWebSignature.scala:28)
authentikat.jwt.JsonWebToken$.validate(JsonWebToken.scala:85)

**Comment by jasongoodwin** [comment]
Should be on 1.0. Let me have a look tonight - I need to publish.

**Comment by yogeshpathade** [comment]
Thanks Json. The 1.0.0 code does have the implementation for RS256.
I will get the 1.0.0 for my app.
